spacing = 20
scaling = "linear"
target_crs = "4326"
ncpu = "4"
mem = "40"
queue = "normal"
project = "u46"
walltime = "02:00:00"
orbit_dir = "/g/data/fj7/Copernicus/Sentinel-1/"
orbit_type = "POE"
output_dir = "/g/data/<project>/projects/sar-antarctica-processing/s1_rtc"
gamma_lib_dir = "/g/data/dg9/GAMMA/GAMMA_SOFTWARE-20230712"
gamma_env_var = "/g/data/<project>/<username>/micromamba/envs/sar-pipeline/lib:/g/data/<project>/<username>/gamma_symlinks"