scene = "/g/data/fj7/Copernicus/Sentinel-1/C-SAR/GRD/2022/2022-01/65S110E-70S115E/S1A_EW_GRDM_1SDH_20220117T122010_20220117T122115_041500_04EF6B_6437.zip"

[gamma]
path = "/g/data/dg9/GAMMA/GAMMA_SOFTWARE-20230712"
required_libs = "/g/data/yp75/projects/pyrosar_processing/s1-rtc-pyrosar-notebook:/apps/fftw3/3.3.10/lib:/apps/gdal/3.6.4/lib64"

[paths]
data = "/g/data/yp75/projects/pyrosar_processing/data"

