name: default
channels:
- conda-forge
- avalentino
- s1-etad
- nodefaults
dependencies:
- geopandas >=1.0.1
- numpy <2.0
- gdal >=3.10.2
- pyproj >=3.7.1
- pyrosar >=0.28.0
- rasterio >=1.4.3
- shapely >=2.0.7
- spatialist >=0.14.0
- s1etad >=0.5.5,<0.6
- s1etad_tools >=0.8.1,<0.9
- python >=3.8
- pip
- pip:
  - -e .
  - affine
  - asf-search
  - boto3
  - botocore
  - click
  - h5py
  - pystac
  - python-dateutil
  - ruamel-yaml
  - tomli

