name: default
channels:
- conda-forge
<<<<<<< HEAD
- avalentino
- s1-etad
- nodefaults
dependencies:
- affine >=2.4.0
- click >=8.1.8
=======
- nodefaults
dependencies:
>>>>>>> 5b6e789 (Update CI to use pixi, add docs)
- geopandas >=1.0.1
- numpy <2.0
- gdal >=3.10.2
- pyproj >=3.7.1
- pyrosar >=0.28.0
- rasterio >=1.4.3
- shapely >=2.0.7
- spatialist >=0.14.0
<<<<<<< HEAD
- s1etad >=0.5.5
- s1etad_tools >=0.8.1
- tomli >=2.2.1
- sentineleof >=0.11.0
=======
>>>>>>> 5b6e789 (Update CI to use pixi, add docs)
- python >=3.8
- pip
- pip:
  - -e .
<<<<<<< HEAD
  - asf-search>=8.1.1
  - boto3>=1.37.27
  - botocore>=1.37.27
  - h5py>=3.13.0
  - pystac>=1.12.2
  - ruamel-yaml>=0.18.10
  - s1-orbits>=0.1.3
=======
  - affine
  - asf-search
  - boto3
  - botocore
  - click
  - h5py
  - pystac
  - python-dateutil
  - ruamel-yaml
  - tomli

>>>>>>> 5b6e789 (Update CI to use pixi, add docs)
