name: sar-pipeline
channels:
- conda-forge
- avalentino
- s1-etad
- nodefaults
dependencies:
- affine >=2.4.0
- click >=8.1.8
- geopandas >=1.0.1
- numpy <2.0
- gdal >=3.10.2
- pyproj >=3.7.1
- pyrosar >=0.32.0,<0.33
- rasterio >=1.4.3
- shapely >=2.0.7
- spatialist >=0.14.0,<0.17
- s1etad >=0.5.5
- s1etad_tools >=0.8.1
- tomli >=2.2.1
- s1reader >=0.2.4
- aioboto3 ==14.1.0
- s3fs >=2026.3.0,<2027
- python >=3.8
- pip
- pip:
  - -e .
  - asf-search>=9.0.9
  - boto3>=1.37.1
  - botocore>=1.37.1
  - h5py>=3.13.0
  - ruamel-yaml>=0.18.10
  - s1-orbits>=0.1.3
  - cdsetool @ git+https://github.com/CDSETool/CDSETool.git
  - python-dotenv>=1.1.1, <2
  - pystac[validation]==1.13.0
  - antimeridian>=0.4.3, <0.5
  - dem-handler @ git+https://github.com/GeoscienceAustralia/dem-handler.git@v0.2.6
  - odc-stac>=0.5.0, <0.6
  - pystac-client>=0.9.0, <0.10
  - sentineleof @ git+https://github.com/scottstanie/sentineleof@v0.11.2
  - tqdm>=4.67.1, <5
  - pooch>=1.9.0, <2
  - ipykernel>=7.3.0, <8
  - ipywidgets>=8.1.9, <9
  - black[jupyter]==26.3.1
  - stac-geoparquet>=0.7.0, <0.8
  - docker>=7.1.0, <8
