[build-system]
requires = ["setuptools>=61.0", "setuptools_scm[toml]>=6.2"]
build-backend = "setuptools.build_meta"

[project]
name = "sar-pipeline"
requires-python = ">=3.8"
authors = [
    {name="Geoscience Australia", email="DigitalEarthAntarctica@ga.gov.au"},
]
description = "Antarctic SAR Backscatter Processing Pipeline"
classifiers=[
    "Intended Audience :: Science/Research",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
]
dynamic = ["version"]
dependencies = [ 
    "asf-search>=9.0.9", 
    "boto3>=1.37.1", 
    "botocore>=1.37.1", 
    "h5py>=3.13.0", 
    "ruamel-yaml>=0.18.10", 
    "s1-orbits>=0.1.3", 
    "cdsetool @ git+https://github.com/CDSETool/CDSETool.git", 
    "python-dotenv>=1.1.1,<2", 
    "pystac[validation]==1.13.0", 
    "antimeridian>=0.4.3,<0.5", 
    "dem-handler @ git+https://github.com/GeoscienceAustralia/dem-handler.git@v0.2.6", 
]

[project.urls]
Homepage = "https://github.com/GeoscienceAustralia/sar-pipleine.git"
# Documentation = "XXX"

[project.scripts]
### GENERAL ###
upload-files-in-folder-to-s3 = "sar_pipeline.pipelines.pyrosar_gamma.nci.cli:upload_files_in_folder_to_s3"
get-burst-ids-for-scene = "sar_pipeline.pipelines.isce3_rtc.cli:get_bursts_ids_for_scene"
download-etad = "sar_pipeline.preparation.cli:download_etad"
### NCI / PYROSAR_GAMMA ###
nci-find-scene = "sar_pipeline.pipelines.pyrosar_gamma.nci.cli:find_scene_file"
nci-find-orbits = "sar_pipeline.pipelines.pyrosar_gamma.nci.cli:find_orbits_for_scene"
nci-pyrosar-gamma-rtc-run-workflow = "sar_pipeline.pipelines.pyrosar_gamma.nci.cli:run_pyrosar_gamma_workflow"
nci-pyrosar-gamma-rtc-submit-workflow = "sar_pipeline.pipelines.pyrosar_gamma.nci.cli:submit_pyrosar_gamma_workflow"
## ISCE3_RTC ###
isce3-rtc-get-data-for-scene-and-make-run-config = "sar_pipeline.pipelines.isce3_rtc.cli:get_data_for_scene_and_make_run_config"
isce3-rtc-make-metadata-and-upload-bursts = "sar_pipeline.pipelines.isce3_rtc.cli:make_metadata_and_upload_bursts"
isce3-rtc-compare-products = "sar_pipeline.pipelines.isce3_rtc.cli:compare_products"

[tool.setuptools_scm]
version_file = "sar_pipeline/_version.py"

[tool.pytest.ini_options]
testpaths = ["tests/*"]

[tool.setuptools.packages.find]
where = ["."]

[tool.setuptools.package-data]
sar_pipeline = ["**/*.yaml", "**/*.yml", "**/*.gpkg", "**/*.json"]

[tool.pixi.workspace]
channels = ["conda-forge", "avalentino", "s1-etad"]
platforms = ["linux-64", "osx-arm64"]

[tool.pixi.pypi-dependencies]
sar-pipeline = { path = ".", editable = true }

[tool.pixi.dependencies]
affine = ">=2.4.0"
click = ">=8.1.8"
geopandas = ">=1.0.1"
numpy = "<2.0"
gdal = ">=3.10.2"
pyproj = ">=3.7.1"
pyrosar = ">=0.32.0,<0.33"
rasterio = ">=1.4.3"
shapely = ">=2.0.7"
spatialist = ">=0.14.0,<0.17"
s1etad = ">=0.5.5"
s1etad_tools = ">=0.8.1"
tomli = ">=2.2.1"
sentineleof = ">=0.11.0"
s1reader = ">=0.2.4"
aioboto3 = "==14.1.0"

[tool.pixi.environments]
default = { solve-group = "default" }
dev = { features = ["dev"], solve-group = "default" }

[tool.pixi.feature.dev.tasks]
### TEST RELATED TASKS ###
# run all tests
test-all = "pytest"

### Shared Pipeline Tests ###
# tests do not require credentials - can currently be run locally and in github
test-pipeline-no-creds = 'pixi run install-pygssearch-env && export PYGSSEARCH_CONDA_ENV="$(conda info --base)/envs/pygssearch-env" && pytest tests/sar_pipeline/ --ignore=tests/sar_pipeline/isce3_rtc'
test-scene-data-source-queries='pixi run install-pygssearch-env && export PYGSSEARCH_CONDA_ENV="$(conda info --base)/envs/pygssearch-env" && pytest tests/sar_pipeline/test_scenes.py -o log_cli=true --capture=tee-sys --log-cli-level=INFO -v -s'

### ISCE3_RTC Pipeline Tests ###
# Tests require credentials - not currently setup for github but should be run locally before PRs
test-isce3-rtc = "pytest tests/sar_pipeline/isce3_rtc -o log_cli=true --capture=tee-sys --log-cli-level=INFO -v -s"
test-isce3-rtc-full-docker-workflow-run = "pixi run export-conda && pytest tests/sar_pipeline/isce3_rtc/test_full_docker_workflow_run.py -o log_cli=true --capture=tee-sys --log-cli-level=INFO -v -s"
test-isce3-rtc-burst-utils = "pytest tests/sar_pipeline/isce3_rtc/test_burst_utils.py -o log_cli=true --capture=tee-sys --log-cli-level=INFO -v -s"
test-isce3-rtc-cli-make-metadata-and-upload-bursts = "pytest tests/sar_pipeline/isce3_rtc/test_cli_make_metadata_and_upload_bursts.py -o log_cli=true --capture=tee-sys --log-cli-level=INFO -v -s"
test-isce3-rtc-cli-get-data-for-scene-and-make-run-config = "pytest tests/sar_pipeline/isce3_rtc/test_cli_get_data_for_scene_and_make_run_config.py -o log_cli=true --capture=tee-sys --log-cli-level=INFO -v -s"
test-isce3-rtc-downloads= 'pixi run install-pygssearch-env && export PYGSSEARCH_CONDA_ENV="$(conda info --base)/envs/pygssearch-env" && pytest tests/sar_pipeline/isce3_rtc/test_downloads.py -o log_cli=true --capture=tee-sys --log-cli-level=INFO -v -s'

### NCI Pipeline Tests ###
# nci specific tests that should be run locally on the nci
test-nci-filesystem = "pytest tests/filesystem"

### GENERAL TASKS ###
lint = "black sar_pipeline"

[tool.black]
target-version = ["py310", "py311", "py312"]

[tool.pixi.feature.dev.dependencies]
pre-commit = ">=4.2.0"
pytest = ">=8.3.5"
coverage = ">=7.8.0"

[tool.pixi.tasks]
export-conda = """
pixi workspace export conda-environment environment.yaml --environment default && \
sed -ix "s/^name: .*/name: sar-pipeline/" environment.yaml; rm environment.yamlx
"""
install-pygssearch-env = """
conda env list | grep -q pygssearch-env || conda env create -f Conda/pygssearch/environment.yaml -n pygssearch-env
"""

[dependency-groups]
dev = ["black==26.3.0", "pytest-dependency>=0.6.0,<0.7"]
