from sar_pipeline.aws.metadata.filetypes import UPDATED_METADATA_PARAMETERS

TIF_UPDATED_METADATA_PARAMETERS = {
    "CEOS_ANALYSIS_READY_DATA_DOCUMENT_IDENTIFIER": UPDATED_METADATA_PARAMETERS[
        "CEOS_DOC"
    ],
    "CEOS_ANALYSIS_READY_DATA_PRODUCT_TYPE": UPDATED_METADATA_PARAMETERS[
        "CEOS_ARD_TYPE"
    ],
    "CONTACT_INFORMATION": UPDATED_METADATA_PARAMETERS["CONTACT_INFO"],
    "INSTITUTION": UPDATED_METADATA_PARAMETERS["INSTITUTION"],
    "PROJECT": UPDATED_METADATA_PARAMETERS["PROJECT"],
}
