import pystac

RENAME_ASSET_FILETYPES = {
    "_ls_map_geo.tif": "_mask.tif",
    "_gs_ratio_geo.tif": "_gamma0-to-sigma0-ratio.tif",
    "_HH_grd_mli_gamma0-rtc_geo.tif": "_HH-gamma0.tif",  # gets replaced in stac.py script
    "_HV_grd_mli_gamma0-rtc_geo.tif": "_HV-gamma0.tif",  # gets replaced in stac.py script
    "_VV_grd_mli_gamma0-rtc_geo.tif": "_VV-gamma0.tif",  # gets replaced in stac.py script
    "_VH_grd_mli_gamma0-rtc_geo.tif": "_VH-gamma0.tif",  # gets replaced in stac.py script
    "_HH_grd_mli_sigma0-rtc_geo.tif": "_HH-sigma0.tif",  # gets replaced in stac.py script
    "_HV_grd_mli_sigma0-rtc_geo.tif": "_HV-sigma0.tif",  # gets replaced in stac.py script
    "_VV_grd_mli_sigma0-rtc_geo.tif": "_VV-sigma0.tif",  # gets replaced in stac.py script
    "_VH_grd_mli_sigma0-rtc_geo.tif": "_VH-sigma0.tif",  # gets replaced in stac.py script
    "_HH_grd_mli_gamma0-rtc_geo_db.tif": "_HH-gamma0_db.tif",  # gets replaced in stac.py script
    "_HV_grd_mli_gamma0-rtc_geo_db.tif": "_HV-gamma0_db.tif",  # gets replaced in stac.py script
    "_VV_grd_mli_gamma0-rtc_geo_db.tif": "_VV-gamma0_db.tif",  # gets replaced in stac.py script
    "_VH_grd_mli_gamma0-rtc_geo_db.tif": "_VH-gamma0_db.tif",  # gets replaced in stac.py script
    "_HH_grd_mli_sigma0-rtc_geo_db.tif": "_HH-sigma0_db.tif",  # gets replaced in stac.py script
    "_HV_grd_mli_sigma0-rtc_geo_db.tif": "_HV-sigma0_db.tif",  # gets replaced in stac.py script
    "_VV_grd_mli_sigma0-rtc_geo_db.tif": "_VV-sigma0_db.tif",  # gets replaced in stac.py script
    "_VH_grd_mli_sigma0-rtc_geo_db.tif": "_VH-sigma0_db.tif",  # gets replaced in stac.py script
    "_inc_geo.tif": "_local-incidence-angle.tif",
    # "_incidence_angle.tif": "_incidence-angle.tif",
    "_dem_seg_geo.tif": "_digital-elevation-model.tif",
    # ".png": "_thumbnail.png",
}

REQUIRED_ASSET_FILETYPES = {
    "gamma0": [
        "_HH-gamma0.tif",
        "_HV-gamma0.tif",
        "_VV-gamma0.tif",
        "_VH-gamma0.tif",
        "_HH-gamma0_db.tif",
        "_HV-gamma0_db.tif",
        "_VV-gamma0_db.tif",
        "_VH-gamma0_db.tif",
        "_mask.tif",
        "_local-incidence-angle.tif",
        "_gamma0-to-sigma0-ratio.tif",
        # "_thumbnail.png",
        # "_checksum.sha1",
    ],
    "sigma0": [
        "_HH-sigma0.tif",
        "_HV-sigma0.tif",
        "_VV-sigma0.tif",
        "_VH-sigma0.tif",
        "_HH-sigma0_db.tif",
        "_HV-sigma0_db.tif",
        "_VV-sigma0_db.tif",
        "_VH-sigma0_db.tif",
        "_mask.tif",
        "_local-incidence-angle.tif",
        "_gamma0-to-sigma0-ratio.tif",
        # "_thumbnail.png",
        # "_checksum.sha1",
    ],
}


ASSET_FILETYPE_TO_TITLE = {
    "_mask.tif": "oa_layover_shadow_mask",
    "_number-of-looks.tif": "oa_number_of_looks",
    "_gamma0-to-beta0-ratio.tif": "oa_gamma0_to_beta0_ratio",
    "_gamma0-to-sigma0-ratio.tif": "oa_gamma0_to_sigma0_ratio",
    "_HH-gamma0.tif": "hh_gamma0",
    "_HV-gamma0.tif": "hv_gamma0",
    "_VV-gamma0.tif": "vv_gamma0",
    "_VH-gamma0.tif": "vh_gamma0",
    "_HH-sigma0.tif": "hh_sigma0",
    "_HV-sigma0.tif": "hv_sigma0",
    "_VV-sigma0.tif": "vv_sigma0",
    "_VH-sigma0.tif": "vh_sigma0",
    "_HH-beta0.tif": "hh_beta0",
    "_HV-beta0.tif": "hv_beta0",
    "_VV-beta0.tif": "vv_beta0",
    "_VH-beta0.tif": "vh_beta0",
    "_HH-gamma0_db.tif": "hh_gamma0_db",
    "_HV-gamma0_db.tif": "hv_gamma0_db",
    "_VV-gamma0_db.tif": "vv_gamma0_db",
    "_VH-gamma0_db.tif": "vh_gamma0_db",
    "_HH-sigma0_db.tif": "hh_sigma0_db",
    "_HV-sigma0_db.tif": "hv_sigma0_db",
    "_VV-sigma0_db.tif": "vv_sigma0_db",
    "_VH-sigma0_db.tif": "vh_sigma0_db",
    "_HH-beta0_db.tif": "hh_beta0_db",
    "_HV-beta0_db.tif": "hv_beta0_db",
    "_VV-beta0_db.tif": "vv_beta0_db",
    "_VH-beta0_db.tif": "vh_beta0_db",
    "_local-incidence-angle.tif": "oa_local_incidence_angle",
    "_incidence-angle.tif": "oa_incidence_angle",
    "_interpolated-dem.tif": "oa_digital_elevation_model",
    "_thumbnail.png": "thumbnail",
    "_checksum.sha1": "checksum",
}

ASSET_FILETYPE_TO_DESCRIPTION = {
    "_mask.tif": "shadow layover data mask",
    "_number-of-looks.tif": "number of looks",
    "_gamma0-to-beta0-ratio.tif": "backscatter conversion layer, gamma0 to beta0. Eq. beta0 = rtc_anf_gamma0_to_beta0*gamma0",
    "_gamma0-to-sigma0-ratio.tif": "backscatter conversion layer, gamma0 to sigma0. Eq. sigma0 = rtc_anf_sigma0_to_sigma0*gamma0",
    "_HH-gamma0.tif": "HH polarised gamma0 linear backscatter",
    "_HV-gamma0.tif": "HV polarised gamma0 linear backscatter",
    "_VV-gamma0.tif": "VV polarised gamma0 linear backscatter",
    "_VH-gamma0.tif": "VH polarised gamma0 linear backscatter",
    "_HH-sigma0.tif": "HH polarised sigma0 linear backscatter",
    "_HV-sigma0.tif": "HV polarised sigma0 linear backscatter",
    "_VV-sigma0.tif": "VV polarised sigma0 linear backscatter",
    "_VH-sigma0.tif": "VH polarised sigma0 linear backscatter",
    "_HH-beta0.tif": "HH polarised beta0 linear backscatter",
    "_HV-beta0.tif": "HV polarised beta0 linear backscatter",
    "_VV-beta0.tif": "VV polarised beta0 linear backscatter",
    "_VH-beta0.tif": "VH polarised beta0 linear backscatter",
    "_HH-gamma0_db.tif": "HH polarised gamma0 log backscatter",
    "_HV-gamma0_db.tif": "HV polarised gamma0 log backscatter",
    "_VV-gamma0_db.tif": "VV polarised gamma0 log backscatter",
    "_VH-gamma0_db.tif": "VH polarised gamma0 log backscatter",
    "_HH-sigma0_db.tif": "HH polarised sigma0 log backscatter",
    "_HV-sigma0_db.tif": "HV polarised sigma0 log backscatter",
    "_VV-sigma0_db.tif": "VV polarised sigma0 log backscatter",
    "_VH-sigma0_db.tif": "VH polarised sigma0 log backscatter",
    "_HH-beta0_db.tif": "HH polarised beta0 log backscatter",
    "_HV-beta0_db.tif": "HV polarised beta0 log backscatter",
    "_VV-beta0_db.tif": "VV polarised beta0 log backscatter",
    "_VH-beta0_db.tif": "VH polarised beta0 log backscatter",
    "_local-incidence-angle.tif": "local incidence angle (LIA)",
    "_incidence-angle.tif": "incidence angle (IA)",
    "_interpolated-dem.tif": "interpolated digital elevation model (DEM)",
    "_thumbnail.png": "thumbnail image for backscatter",
    "_checksum.sha1": "product folder checksum file",
}

ASSET_FILETYPE_TO_ROLES = {
    "_mask.tif": ["data", "auxiliary", "mask", "shadow", "layover"],
    "_number-of-looks.tif": ["data", "auxiliary"],
    "_gamma0-to-beta0-ratio.tif": ["data", "auxiliary", "conversion"],
    "_gamma0-to-sigma0-ratio.tif": ["data", "auxiliary", "conversion"],
    "_HH-gamma0.tif": ["data", "backscatter"],
    "_HV-gamma0.tif": ["data", "backscatter"],
    "_VV-gamma0.tif": ["data", "backscatter"],
    "_VH-gamma0.tif": ["data", "backscatter"],
    "_HH-sigma0.tif": ["data", "backscatter"],
    "_HV-sigma0.tif": ["data", "backscatter"],
    "_VV-sigma0.tif": ["data", "backscatter"],
    "_VH-sigma0.tif": ["data", "backscatter"],
    "_HH-beta0.tif": ["data", "backscatter"],
    "_HV-beta0.tif": ["data", "backscatter"],
    "_VV-beta0.tif": ["data", "backscatter"],
    "_VH-beta0.tif": ["data", "backscatter"],
    "_HH-gamma0_db.tif": ["data", "backscatter"],
    "_HV-gamma0_db.tif": ["data", "backscatter"],
    "_VV-gamma0_db.tif": ["data", "backscatter"],
    "_VH-gamma0_db.tif": ["data", "backscatter"],
    "_HH-sigma0_db.tif": ["data", "backscatter"],
    "_HV-sigma0_db.tif": ["data", "backscatter"],
    "_VV-sigma0_db.tif": ["data", "backscatter"],
    "_VH-sigma0_db.tif": ["data", "backscatter"],
    "_HH-beta0_db.tif": ["data", "backscatter"],
    "_HV-beta0_db.tif": ["data", "backscatter"],
    "_VV-beta0_db.tif": ["data", "backscatter"],
    "_VH-beta0_db.tif": ["data", "backscatter"],
    "_local-incidence-angle.tif": ["data", "auxiliary"],
    "_incidence-angle.tif": ["data", "auxiliary"],
    "_interpolated-dem.tif": ["data", "ancillary"],
    "_thumbnail.png": ["thumbnail"],
    "_checksum.sha1": ["checksum", "metadata"],
}

ASSET_FILETYPE_TO_MEDIATYPE = {
    "_mask.tif": pystac.media_type.MediaType.COG,
    "_number-of-looks.tif": pystac.media_type.MediaType.COG,
    "_gamma0-to-beta0-ratio.tif": pystac.media_type.MediaType.COG,
    "_gamma0-to-sigma0-ratio.tif": pystac.media_type.MediaType.COG,
    "_HH-gamma0.tif": pystac.media_type.MediaType.COG,
    "_HV-gamma0.tif": pystac.media_type.MediaType.COG,
    "_VV-gamma0.tif": pystac.media_type.MediaType.COG,
    "_VH-gamma0.tif": pystac.media_type.MediaType.COG,
    "_HH-sigma0.tif": pystac.media_type.MediaType.COG,
    "_HV-sigma0.tif": pystac.media_type.MediaType.COG,
    "_VV-sigma0.tif": pystac.media_type.MediaType.COG,
    "_VH-sigma0.tif": pystac.media_type.MediaType.COG,
    "_HH-beta0.tif": pystac.media_type.MediaType.COG,
    "_HV-beta0.tif": pystac.media_type.MediaType.COG,
    "_VV-beta0.tif": pystac.media_type.MediaType.COG,
    "_VH-beta0.tif": pystac.media_type.MediaType.COG,
    "_HH-gamma0_db.tif": pystac.media_type.MediaType.COG,
    "_HV-gamma0_db.tif": pystac.media_type.MediaType.COG,
    "_VV-gamma0_db.tif": pystac.media_type.MediaType.COG,
    "_VH-gamma0_db.tif": pystac.media_type.MediaType.COG,
    "_HH-sigma0_db.tif": pystac.media_type.MediaType.COG,
    "_HV-sigma0_db.tif": pystac.media_type.MediaType.COG,
    "_VV-sigma0_db.tif": pystac.media_type.MediaType.COG,
    "_VH-sigma0_db.tif": pystac.media_type.MediaType.COG,
    "_HH-beta0_db.tif": pystac.media_type.MediaType.COG,
    "_HV-beta0_db.tif": pystac.media_type.MediaType.COG,
    "_VV-beta0_db.tif": pystac.media_type.MediaType.COG,
    "_VH-beta0_db.tif": pystac.media_type.MediaType.COG,
    "_local-incidence-angle.tif": pystac.media_type.MediaType.COG,
    "_incidence-angle.tif": pystac.media_type.MediaType.COG,
    "_interpolated-dem.tif": pystac.media_type.MediaType.COG,
    "_thumbnail.png": pystac.media_type.MediaType.PNG,
    "_checksum.sha1": pystac.media_type.MediaType.TEXT,
}
