spacing = 40
scaling = "linear"
ncpu = "4"
mem = "32"
queue = "normal"
project = "u46"
walltime = "04:00:00"
output_dir = "/g/data/yp75/projects/sar-antractica-processing/pyrosar_gamma/"
gamma_lib_dir = "/g/data/dg9/GAMMA/GAMMA_SOFTWARE-20230712"
gamma_env_var = "/g/data/yp75/projects/pyrosar_processing/sar-pyrosar-nci:/apps/fftw3/3.3.10/lib:/apps/gdal/3.6.4/lib64"