name: Linting

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Run black linting
    steps:
    - uses: actions/checkout@v4
    - name: Lint
      uses: psf/black@26.3.0
      with:
        options: "--check --verbose sar_pipeline"